# Generated by Django 5.0.7 on 2024-08-08 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convmessages",
            old_name="created_by",
            new_name="User",
        ),
    ]
